version: "3.9"

services:
  access_service:
    build: 
      context: ../access_service
      dockerfile: Dockerfile
    container_name: access_service
    command: "poetry run uvicorn --factory access_service.presentation.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../access_service/.env
    volumes:
      - ../access_service/src/:/app/src/
    ports:
      - "8000:8000"