services:
  postgres:
    container_name: messenger_postgres
    image: postgres:alpine
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - common_network 

networks:
  common_network:
    external: true

volumes:
  postgres_data: