services:
  redis:
    container_name: messenger_redis
    image: redis:alpine
    env_file:
      - ../.env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - common_network 

networks:
  common_network:
    external: true