services:
  postgres:
    container_name: access_service_postgres
    image: postgres:alpine
    env_file:
      - ../access_service/.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
