services:
  postgres:
    container_name: access_service_postgres
    image: postgres:alpine
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: access_service_redis
    image: redis:alpine
    env_file:
      - ../.env
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"

  kafka: 
    




volumes:
  postgres_data:
