[web]
cors-allow = ['http://localhost:5173']

[email]
activation-mail-subject = 'ЗАВЕРШИТЕ РЕГИСТРАЦИЮ В ZAMETKA'
activation-email-template-path = 'zametka.access_service.presentation.http'
activation-email-template-name = 'confirmation-mail.html'

[smtp]
use-tls = true
host = 'smtp.yandex.ru'
port = 465

[security]
algorithm = 'HS256'
access-token-expires-minutes = 10
confirmation-token-expires-minutes = 1
refresh-token-expires-days = 15

[auth]
access-token-key = 'access'
refresh-token-key = 'refresh'