"""phone_number -> int

Revision ID: 4830010c325a
Revises: 5b3a3a3c1362
Create Date: 2024-10-21 21:33:59.182175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4830010c325a'
down_revision: Union[str, None] = '5b3a3a3c1362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="phone_number::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.Integer(),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
